export  const EcomBannerData = {
  heading: "Seeking customized e-commerce web solutions? We offer specialized expertise.",
  description: `The eCommerce website has revolutionized the way customers shop and provides businesses with a multitude of new opportunities to market their products and services. American Design Network’s team provides tailored web solutions to enhance your journey towards achieving your goals effortlessly. We are committed to pushing the boundaries of eCommerce design and implementation with our expert team, offering an array of features to attract and convert customers. We will handle your project with professionalism and creativity, ensuring your customers enjoy an exceptional shopping experience!`,
   categories: [
    "Custom Store Design",
    "Shopping Cart Development",
    "Payment Gateway Integration",
    "Product Management System",
    "Multi-Vendor Marketplace",
    "Mobile Commerce (mCommerce)",
    "Ecommerce SEO & Marketing"
  ],
  image: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1756306998/EWD_zobj7w.png", 
};



export const ecommercePricingData = [
  {
    heading: "E-Commerce Basic Package",
    price: 599,
    cutPrice: 999,
    bestSeller: false,
    lists: {
      1: "E-Commerce Website Design and Development",
      2: "Theme Based Design",
      3: "2 Banner Designs",
      4: "3 Stock Images",
      5: "Sliding Banner",
      6: "06 Revisions",
      7: "Up to 10 Products",
      8: "Up to 3 Categories",
      9: "Content/Inventory Management System",
      10: "Easy Product Search Bar",
      11: "Online Payment Integration (Optional)",
      12: "Shopping Cart Integration",
      13: "Payment Module Integration",
      14: "Direct Checkout",
      15: "Signup Checkout",
      16: "Tax Calculator Integration",
      17: "Shipping Calculator Integration",
      18: "Wishlist",
      19: "Complete W3C Certified HTML",
      20: "Dedicated Team of Designers and Developers",
      21: "Complete Deployment",
    },
  },
  {
    heading: "E-Commerce Startup Package",
    price: 799,
    cutPrice: 1399,
    bestSeller: true,
    lists: {
      1: "E-Commerce Website Design and Development",
      2: "High-end Theme Based Design",
      3: "5 Banner Designs",
      4: "Sliding Banner",
      5: "5 Stock Photos",
      6: "12 Revisions",
      7: "Hover Effects",
      8: "Up to 25 Products",
      9: "Up to 5 Categories",
      10: "Content/Inventory Management System",
      11: "Easy Product Search Bar",
      12: "Online Payment Integration (Optional)",
      13: "Shopping Cart Integration",
      14: "Payment Module Integration",
      15: "Direct Checkout",
      16: "Signup Checkout",
      17: "Tax Calculator Integration",
      18: "Shipping Calculator Integration",
      19: "Social Media Pages Integration",
      20: "Facebook 'Like' Plugin Integration",
      21: "Wishlist",
      22: "Sitemap",
      23: "Complete W3C Certified HTML",
      24: "Dedicated Team of Designers and Developers",
      25: "Complete Deployment",
    },
  },
  {
    heading: "E-Commerce Pro Package",
    price: 1299,
    cutPrice: 2399,
    bestSeller: false,
    lists: {
      1: "E-Commerce Website Design and Development",
      2: "Customized Theme Based Design",
      3: "7 Banner Designs",
      4: "Sliding Banner",
      5: "7 Stock Photos",
      6: "Unlimited Revisions",
      7: "Hover Effects",
      8: "Up to 100 Products",
      9: "Up to 10 Categories",
      10: "Content/Inventory Management System",
      11: "Easy Product Search Bar",
      12: "Online Payment Integration (Optional)",
      13: "Shopping Cart Integration",
      14: "Payment Module Integration",
      15: "Direct Checkout",
      16: "Signup Checkout",
      17: "Tax Calculator Integration",
      18: "Shipping Calculator Integration",
      19: "Wishlist",
      20: "Import/Export Order",
      21: "Bulk Import/Export of Order Information",
      22: "Search Engine Submission",
      23: "SEO Friendly",
      24: "Web Analytics Integration",
      25: "Monthly Traffic Reporting",
      26: "Social Media Pages Integration",
      27: "Facebook 'Like' Plugin Integration",
      28: "Sitemap",
      29: "Complete W3C Certified HTML",
      30: "Dedicated Team of Designers and Developers",
      31: "Complete Deployment",
    },
  },
  {
    heading: "E-Commerce Identity Package",
    price: 1699,
    cutPrice: 3399,
    bestSeller: true,
    lists: {
      1: "E-Commerce Website Design and Development",
      2: "Customized Tailor-Made Design",
      3: "Professional, Modern, Unique Design",
      4: "10 Banner Designs",
      5: "Sliding Banner",
      6: "10 Stock Photos",
      7: "Unlimited Revisions",
      8: "Special Hover Effects",
      9: "Up to 500 Products",
      10: "Up to 25 Categories",
      11: "Product Reviews and Ratings",
      12: "Mobile Responsive",
      13: "User Sign Up, Sign In & Dashboard Area",
      14: "Auto Email for Profile Validation & Notification(s)",
      15: "Content/Inventory Management System",
      16: "Easy Product Search Bar",
      17: "Online Payment Integration (Optional)",
      18: "Shopping Cart Integration",
      19: "Payment Module Integration",
      20: "Direct Checkout",
      21: "Tax & Shipping Calculator Integration",
      22: "Wishlist",
      23: "Import/Export Order",
      24: "Bulk Import/Export of Order Information",
      25: "Search Engine Submission",
      26: "SEO Friendly",
      27: "Web Analytics Integration",
      28: "Monthly Traffic Reporting",
      29: "Social Media Pages Integration",
      30: "Facebook 'Like' Plugin Integration",
      31: "Blog Page (If Required)",
      32: "Sitemap",
      33: "Complete W3C Certified HTML",
      34: "Dedicated Team of Designers and Developers",
      35: "Complete Deployment",
    },
  },
  {
    heading: "E-Commerce Business Package",
    price: 2499,
    cutPrice: 4999,
    bestSeller: false,
    lists: {
      1: "Customized Tailor-Made Design",
      2: "Professional, Modern, Unique Design",
      3: "User-friendly Navigation",
      4: "20 Banner Designs",
      5: "20 Stock Photos",
      6: "Unlimited Revisions",
      7: "Special Hover Effects",
      8: "Unlimited Products & Categories",
      9: "Product Summary Reports",
      10: "Multiple Filtration & Sorting Options",
      11: "Product Detail with Similar Product Range",
      12: "Coupon Code Generation",
      13: "Product Comparison",
      14: "Mobile Responsive",
      15: "User Profile & Dashboard Management",
      16: "Discounted/New Arrival Product Showcase",
      17: "Discount Coupons",
      18: "Multiple Currency Integration",
      19: "Bulk Product Upload & Export",
      20: "Live Chat Integration",
      21: "SEO & Analytics Integration",
      22: "Monthly Traffic Reporting",
      23: "Facebook 'Like' Plugin Integration",
      24: "Social Media Pages Integration",
      25: "Blog Page (If Required)",
      26: "Complete Deployment",
    },
  },
  {
    heading: "E-Commerce Corporate Package",
    price: 3699,
    cutPrice: 7398,
    bestSeller: true,
    lists: {
      1: "Customized Tailor-Made Design",
      2: "Professional, Modern, Unique Design",
      3: "User-friendly Navigation",
      4: "20 Banner Designs",
      5: "20 Stock Photos",
      6: "Unlimited Revisions",
      7: "Unlimited Products & Categories",
      8: "Advanced Product Reports & Filters",
      9: "Coupon Code Generation",
      10: "Product Comparison",
      11: "Mobile Responsive",
      12: "Customer Login / Social Login Integration",
      13: "Profile Management (Backend & Frontend)",
      14: "Discount & New Arrival Showcases",
      15: "Bulk Upload & Export Orders",
      16: "Live Chat Integration",
      17: "SEO & Analytics Integration",
      18: "Monthly Traffic Reporting",
      19: "Facebook Shop Setup",
      20: "Social Media Pages Integration",
      21: "Blog Page (If Required)",
      22: "Complete Deployment",
    },
  },
];


export const ecommerceFaqs = [
  {
    question: "What is eCommerce website development?",
    answer:
      "eCommerce website development involves designing and building online stores that allow businesses to sell products or services digitally. It includes storefront design, product management, payment gateway integration, and user experience optimization."
  },
  {
    question: "Why is eCommerce website design important?",
    answer:
      "A well-designed eCommerce site builds trust, improves customer experience, and increases conversion rates. Good design ensures smooth navigation, fast performance, and a visually appealing layout that keeps customers engaged."
  },
  {
    question: "Do you provide custom eCommerce solutions?",
    answer:
      "Yes, we build fully customized eCommerce solutions tailored to your business needs, including unique designs, features, and third-party integrations that match your goals."
  },
  {
    question: "Can you integrate secure payment gateways?",
    answer:
      "Absolutely! We integrate secure and trusted payment gateways like PayPal, Stripe, and credit card processing systems to ensure safe and seamless transactions for your customers."
  },
  {
    question: "Will my eCommerce site be mobile-friendly?",
    answer:
      "Yes, every eCommerce website we design is fully responsive and mobile-optimized, ensuring a smooth shopping experience across all devices — desktops, tablets, and smartphones."
  },
  {
    question: "Do you provide product management features?",
    answer:
      "Yes, we implement easy-to-use dashboards where you can add, update, and manage your products, categories, pricing, and inventory efficiently."
  },
  {
    question: "Do you offer SEO-friendly eCommerce development?",
    answer:
      "Yes, our eCommerce websites are built with SEO best practices in mind, helping your store rank better on search engines and attract more organic traffic."
  }
];



export default EcomBannerData;