export const tabData = [
   { label: "All", content: [] },
  {
    label: "Logo Design",
    content: [
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Agriculture" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Agriculture" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Agriculture" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Agriculture" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Agriculture" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-3.jpg",name:"Animals" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Apparel" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Architecture" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Art & Craft" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-3.jpg",name:"Beauty" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Business Solutions" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Church" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Construction" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-3.jpg",name:"Consultant" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Ecommerce" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Education" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Engineering" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-3.jpg",name:"Event Management" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Finance" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Food" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Games" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-3.jpg",name:"Health" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Insurance" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Jewlery" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Kids & Toys" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-3.jpg",name:"Law Firm" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Logistics" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Manufacturing" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Marketing" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-3.jpg",name:"Medical & Dental" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Photography" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Salon & Spa" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Smoking & Vaping" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg",name:"Technology" },
    ],
  },
  {
    label: "Website Design And Development",
    content: [
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
    ],
  },
  {
    label: "Branding",
    content: [
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
    ],
  },
  {
    label: "Ecommerce Websites",
    content: [
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
    ],
  },
  {
    label: "Mobile Apps",
    content: [
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
    ],
  },
  {
    label: "Wordpress Development",
    content: [
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
      { type: "image", src: "https://res.cloudinary.com/dpm8fa6gn/image/upload/v1736881243/cld-sample-5.jpg" },
    ],
  },
    {
    label: "Video Animation",
    content: [
      { type: "video", src: "https://www.w3schools.com/html/mov_bbb.mp4" },
      { type: "video", src: "https://www.w3schools.com/html/movie.mp4" },
    ],
  },
];